base_config:
  - ./dgn.yaml

# the path of algorithm class
algorithm_path: agents.ac_dgn.ActorCriticDGNAgent
trainer_path: trainers.actor_critic_trainer.ActorCriticTrainer

# RL-related params
soft_update_target_network: true
tau: 0.99

training_action_mode: epsilon-categorical
testing_action_mode: epsilon-categorical